# Use an official Nvidia CUDA runtime as a parent image
FROM nvidia/cuda:12.4.1-devel-ubuntu22.04

WORKDIR /app

# Copy large prebuilt whl file to avoid github lfs charges
COPY prebuilt_wheels /app/prebuilt_wheels
