name: build_and_push

on:
  workflow_dispatch:

jobs:
  build-and-push-image:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with: 
          lfs: true

      - name: Delete huge unnecessary tools folder
        run: rm -rf /opt/hostedtoolcache

      # - name: Compute SHA-256 checksum
      #   run: |
      #     shasum -a 256 prebuilt_wheels/flash_attn-2.7.4.post1-cp310-cp310-linux_x86_64.whl > checksum.txt
      #     cat checksum.txt

      # - name: check unzip 
      #   run: unzip prebuilt_wheels/flash_attn-2.7.4.post1-cp310-cp310-linux_x86_64.whl

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:latest, ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:${{ github.sha }}